name: issue-triage
description: |
  Automatic issue classification workflow that analyzes GitHub issue content
  and assigns appropriate labels, priority, and suggested team assignment.
  Helps maintain consistent issue organization and route work efficiently.
version: "1.0"

inputs:
  - name: title
    type: string
    required: true
    description: Issue title

  - name: body
    type: string
    required: true
    description: Issue description/body text

  - name: author
    type: string
    required: false
    description: Issue author username (for context)

  - name: repository
    type: string
    required: false
    description: Repository name (for domain-specific classification)

steps:
  # Classify issue type and severity
  - id: classify_issue
    name: Issue Classification
    type: llm
    model: fast
    system: |
      You are an expert at triaging software issues. Analyze the issue and classify it.

      **Issue Types:**
      - bug: Something is broken or not working as intended
      - feature: New functionality request
      - enhancement: Improvement to existing functionality
      - documentation: Documentation changes or improvements
      - question: User question or support request
      - refactor: Code cleanup or restructuring
      - performance: Performance-related issue
      - security: Security vulnerability or concern

      **Priority Levels:**
      - critical: Production down, data loss, security breach
      - high: Major functionality broken, affects many users
      - medium: Moderate impact, workaround exists
      - low: Minor issue, cosmetic, or nice-to-have

      **Sentiment:**
      - frustrated: User is clearly frustrated or upset
      - neutral: Standard issue report
      - positive: Feature request or constructive feedback

      Respond in JSON format:
      {
        "type": "bug|feature|enhancement|documentation|question|refactor|performance|security",
        "priority": "critical|high|medium|low",
        "sentiment": "frustrated|neutral|positive",
        "confidence": 0.0-1.0,
        "reasoning": "Brief explanation of classification"
      }
    prompt: |
      Classify this issue:

      **Title:** {{.title}}

      **Body:**
      {{.body}}

      {{if .author}}
      **Author:** {{.author}}
      {{end}}

      {{if .repository}}
      **Repository:** {{.repository}}
      {{end}}

      Provide JSON classification with reasoning.
    timeout: 20
    retry:
      max_attempts: 2
      backoff_base: 2
      backoff_multiplier: 2.0

  # Extract relevant labels
  - id: extract_labels
    name: Label Extraction
    type: llm
    model: fast
    system: |
      Extract relevant labels for this issue based on its content.

      **Available Labels:**
      - Platform: frontend, backend, database, api, cli, mobile
      - Component: auth, ui, workflow, storage, networking, deployment
      - Status: needs-reproduction, needs-design, ready-to-implement
      - Expertise: accessibility, performance, security, i18n
      - Special: breaking-change, good-first-issue, help-wanted

      Respond in JSON format:
      {
        "labels": ["label1", "label2"],
        "reasoning": "Why these labels were selected"
      }

      Only include labels that clearly apply. Maximum 5 labels.
    prompt: |
      Extract labels for this issue:

      **Type:** {{.steps.classify_issue.response}}
      **Priority:** {{.steps.classify_issue.response}}

      **Title:** {{.title}}

      **Body:**
      {{.body}}

      Return JSON with labels array and reasoning.
    timeout: 20

  # Suggest team assignment
  - id: suggest_assignment
    name: Team Assignment Suggestion
    type: llm
    model: fast
    system: |
      Suggest which team should handle this issue based on its classification.

      **Teams:**
      - platform: Core platform, infrastructure, build systems
      - frontend: UI, user experience, client-side functionality
      - backend: Server-side logic, APIs, data processing
      - devops: Deployment, monitoring, CI/CD, cloud infrastructure
      - security: Security vulnerabilities, auth, compliance
      - support: User questions, documentation, onboarding

      Respond in JSON format:
      {
        "team": "platform|frontend|backend|devops|security|support",
        "confidence": 0.0-1.0,
        "reasoning": "Why this team is suggested",
        "requires_multiple_teams": true|false
      }
    prompt: |
      Suggest team assignment for this issue:

      **Type:** {{.steps.classify_issue.response}}
      **Priority:** {{.steps.classify_issue.response}}
      **Labels:** {{.steps.extract_labels.response}}

      **Title:** {{.title}}

      **Summary:** {{.body | truncate 500}}

      Return JSON with team suggestion.
    timeout: 20

  # Generate triage summary
  - id: generate_summary
    name: Generate Triage Summary
    type: llm
    model: balanced
    system: |
      Create a concise triage summary for this issue that can be posted as a comment.

      Format:
      ```markdown
      ## Triage Summary

      **Classification:** [type] - [priority]
      **Labels:** [labels]
      **Suggested Team:** [team]

      **Analysis:**
      [Brief analysis of the issue]

      **Recommended Actions:**
      - [ ] Action item 1
      - [ ] Action item 2

      [Any additional context or notes]
      ```

      Keep it professional, actionable, and helpful.
    prompt: |
      Generate triage summary for this issue:

      **Classification:**
      {{.steps.classify_issue.response}}

      **Labels:** {{.steps.extract_labels.response}}

      **Suggested Team:** {{.steps.suggest_assignment.response}}

      **Original Issue:**
      Title: {{.title}}
      Body: {{.body | truncate 1000}}

      Create a helpful triage summary comment.
    timeout: 30

outputs:
  - name: type
    type: string
    value: "{{.steps.classify_issue.response}}"
    description: Issue type (bug, feature, etc.)

  - name: priority
    type: string
    value: "{{.steps.classify_issue.response}}"
    description: Priority level (critical, high, medium, low)

  - name: labels
    type: array
    value: "{{.steps.extract_labels.response}}"
    description: Suggested labels for the issue

  - name: team
    type: string
    value: "{{.steps.suggest_assignment.response}}"
    description: Suggested team assignment

  - name: summary
    type: string
    value: "{{.steps.generate_summary.response}}"
    description: Markdown-formatted triage summary

  - name: needs_urgent_attention
    type: boolean
    value: "{{.steps.classify_issue.response}}"
    description: Whether this issue requires immediate attention
