run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gofmt         # Check formatting
    - goimports     # Check import ordering
    - govet         # Go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code
    - gosimple      # Suggest code simplifications
    - typecheck     # Type checking
    - misspell      # Check for spelling mistakes
    - revive        # Replacement for golint
    - gosec         # Security checks
    - unconvert     # Remove unnecessary type conversions
    - wrapcheck     # Check that errors are wrapped with context
    - bodyclose     # Check that HTTP response bodies are closed

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  wrapcheck:
    # Allow errors from internal packages to pass through without wrapping
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
    # Allow certain packages to return errors without wrapping
    ignorePackageGlobs:
      - github.com/tombee/conductor/pkg/errors
      - github.com/tombee/conductor/internal/mcp

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude test files from certain checks
    - path: _test\.go
      linters:
        - errcheck
        - gosec
