# GoReleaser configuration for Conductor
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Run tests before building
    - go test ./...
    # Ensure go.mod is tidy
    - go mod tidy

builds:
  - id: conductor
    main: ./cmd/conductor
    binary: conductor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: conductor
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - config.example.yaml

checksum:
  name_template: 'conductor_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other Changes
      order: 999

release:
  github:
    owner: tombee
    name: conductor
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Conductor {{.Version}}

    Download the appropriate binary for your platform, or use the installation script:

    ```bash
    curl -sSL https://raw.githubusercontent.com/tombee/conductor/main/scripts/install.sh | sh
    ```

    ### Installation via Homebrew

    ```bash
    brew tap tombee/tap
    brew install conductor
    ```

brews:
  - name: conductor
    repository:
      owner: tombee
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/tombee/conductor"
    description: "LLM workflow orchestration tool"
    license: "Apache-2.0"
    folder: Formula
    install: |
      bin.install "conductor"
    test: |
      system "#{bin}/conductor", "version"

# Universal Binaries for macOS (combines amd64 and arm64)
universal_binaries:
  - id: conductor
    replace: false
    name_template: '{{ .ProjectName }}'

# SBOM (Software Bill of Materials)
sboms:
  - artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}_
        {{- .Version }}_
        {{- .Os }}_
        {{- .Arch }}.sbom.json

# Metadata for package managers
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
