name: iac-review
description: |
  Analyze Infrastructure as Code changes (Terraform, Pulumi, CDK) to produce
  a risk assessment and operator-friendly change summary. Identifies dangerous
  changes, security implications, and provides clear explanations of what's changing.
version: "1.0"

inputs:
  - name: working_dir
    type: string
    required: false
    default: "."
    description: Path to IaC project directory

  - name: tool
    type: string
    required: false
    default: "terraform"
    description: IaC tool (terraform, pulumi, cdk)

  - name: plan_output
    type: string
    required: false
    description: Pre-generated plan output (skips running the plan command)

  - name: environment
    type: string
    required: false
    default: "unknown"
    description: Target environment (dev, staging, production)

  - name: strict_mode
    type: boolean
    required: false
    default: false
    description: Fail on any HIGH or CRITICAL risk findings

steps:
  # Step 1: Generate the plan (if not provided)
  - id: generate_plan
    name: Generate IaC Plan
    condition: "{{not .inputs.plan_output}}"
    shell.run:
      command: |
        cd {{.inputs.working_dir}}
        {{if eq .inputs.tool "terraform"}}
        terraform plan -no-color -detailed-exitcode 2>&1 || true
        {{else if eq .inputs.tool "pulumi"}}
        pulumi preview --diff --non-interactive 2>&1 || true
        {{else if eq .inputs.tool "cdk"}}
        cdk diff 2>&1 || true
        {{else}}
        echo "Unsupported tool: {{.inputs.tool}}" && exit 1
        {{end}}
    timeout: 300

  # Step 2: Risk Analysis - identify dangerous changes
  - id: risk_analysis
    name: Risk Analysis
    type: llm
    model: balanced
    system: |
      You are an infrastructure security expert analyzing IaC plan output.

      Identify and flag the following risk categories:

      **CRITICAL Risks (block deployment):**
      - Destruction of production databases or persistent storage
      - Removal of backup configurations
      - Security group changes exposing sensitive ports (22, 3389, databases) to 0.0.0.0/0
      - IAM policy changes granting admin/* or overly permissive access
      - Disabling encryption on storage or transit
      - Removing audit logging or monitoring
      - Changes to authentication/authorization systems

      **HIGH Risks (requires approval):**
      - Any resource destruction in production
      - Scaling down (reducing instance counts, memory, CPU)
      - Network topology changes (VPC, subnets, routing)
      - Certificate or secret rotation
      - DNS record modifications
      - Load balancer configuration changes
      - Database configuration changes (even non-destructive)

      **MEDIUM Risks (review recommended):**
      - New IAM roles or policies
      - Security group modifications (not critical)
      - New resources being created
      - Tag changes on critical resources
      - Environment variable changes

      **LOW Risks (informational):**
      - Documentation/description updates
      - Tag additions
      - Non-critical resource updates

      **Anomaly Detection:**
      - Flag unexpected changes (resources being modified that shouldn't be)
      - Identify drift (resources changing that weren't in the commit)
      - Note unusually large change counts
      - Highlight resources changing for the first time

      For each finding, provide:
      1. Risk level (CRITICAL/HIGH/MEDIUM/LOW)
      2. Resource affected (type and name/ID)
      3. What's changing
      4. Why it's risky
      5. Recommended action
    prompt: |
      Analyze this {{.inputs.tool}} plan for risks:

      **Environment:** {{.inputs.environment}}

      **Plan Output:**
      ```
      {{if .inputs.plan_output}}{{.inputs.plan_output}}{{else}}{{.steps.generate_plan.stdout}}{{end}}
      ```

      Provide a structured risk assessment. Group findings by severity.
      Include a risk score (0-100) and deployment recommendation.

      Format as:

      ## Risk Score: X/100

      ## Deployment Recommendation
      [PROCEED / PROCEED_WITH_CAUTION / REQUIRES_APPROVAL / BLOCK]

      ## Critical Risks
      ...

      ## High Risks
      ...

      ## Medium Risks
      ...

      ## Low Risks / Informational
      ...

      ## Anomalies Detected
      ...
    timeout: 60
    retry:
      max_attempts: 2
      backoff_base: 2
      backoff_multiplier: 2.0

  # Step 3: Operator-Friendly Change Summary
  - id: change_summary
    name: Change Summary for Operators
    type: llm
    model: fast
    system: |
      You are a technical writer creating infrastructure change summaries for
      network operators and on-call engineers who need to understand changes quickly.

      Write in plain English. Avoid IaC jargon. Focus on operational impact:

      **What operators care about:**
      - What endpoints/services are affected?
      - Will there be downtime or degraded performance?
      - What ports/protocols are changing?
      - Are there IP address changes?
      - What monitoring/alerting might fire?
      - What rollback steps exist?
      - Are there dependencies that need coordination?

      **Format guidelines:**
      - Use bullet points for easy scanning
      - Group by service/application affected
      - Include before/after for key changes
      - Highlight anything requiring manual intervention
      - Note if changes are reversible vs destructive

      **Avoid:**
      - Terraform/Pulumi/CDK resource type names
      - ARNs or resource IDs (use friendly names)
      - Implementation details (use outcomes)
    prompt: |
      Create an operator-friendly summary of these infrastructure changes:

      **Environment:** {{.inputs.environment}}

      **Raw Plan:**
      ```
      {{if .inputs.plan_output}}{{.inputs.plan_output}}{{else}}{{.steps.generate_plan.stdout}}{{end}}
      ```

      Write a clear summary that a network operator can understand at 3 AM during an incident.

      Format as:

      ## Summary
      [One sentence: what's changing and why it matters]

      ## Services Affected
      - [Service name]: [what's changing]

      ## Network Changes
      - [Any connectivity, routing, DNS changes]

      ## Potential Impact
      - [Downtime expectations]
      - [Performance implications]
      - [Monitoring alerts to expect]

      ## Action Required
      - [Any manual steps needed]
      - [Coordination required]

      ## Rollback
      - [Is this reversible?]
      - [Rollback steps if needed]
    timeout: 45
    retry:
      max_attempts: 2
      backoff_base: 2
      backoff_multiplier: 2.0

  # Step 4: Consolidate into final report
  - id: final_report
    name: Generate Final Report
    type: llm
    model: fast
    system: |
      You are combining a risk analysis and change summary into a single
      deployment review document. Keep both sections intact but add:

      1. An executive summary at the top (2-3 sentences)
      2. A clear GO/NO-GO recommendation
      3. Required approvals based on risk level
    prompt: |
      Combine these analyses into a final IaC change review:

      **Risk Analysis:**
      {{.steps.risk_analysis.response}}

      **Operator Summary:**
      {{.steps.change_summary.response}}

      Create a final report with:
      1. Executive Summary (2-3 sentences)
      2. GO/NO-GO Recommendation
      3. Required Approvals (based on {{.inputs.environment}} and risk level)
      4. Risk Analysis (from above)
      5. Operator Summary (from above)

      For production + CRITICAL/HIGH risks, recommend approval from:
      - Platform team lead
      - Security team (for security-related changes)
      - Database team (for data changes)
    timeout: 30

outputs:
  - name: report
    type: string
    value: "{{.steps.final_report.response}}"
    description: Complete IaC change review report

  - name: risk_score
    type: string
    value: "{{.steps.risk_analysis.response}}"
    description: Detailed risk analysis

  - name: operator_summary
    type: string
    value: "{{.steps.change_summary.response}}"
    description: Operator-friendly change summary

  - name: recommendation
    type: string
    value: "{{.steps.final_report.response}}"
    description: GO/NO-GO recommendation with required approvals
