name: git-branch-code-review
description: Multi-persona code review for git branch changes
version: "1.0"

inputs:
  - name: base_branch
    type: string
    default: "main"
    description: Base branch to compare against

  - name: personas
    type: array
    default: ["security", "performance", "style"]
    description: Review personas to use

  - name: output_file
    type: string
    default: "code-review.md"
    description: Output file for the review report

steps:
  - id: get_branch
    name: Get Current Branch
    shell.run:
      command: ["git", "rev-parse", "--abbrev-ref", "HEAD"]

  - id: get_diff
    name: Get Git Diff
    shell.run: "git diff {{.inputs.base_branch}}...HEAD --stat && echo '---DIFF---' && git diff {{.inputs.base_branch}}...HEAD"

  - id: get_commits
    name: Get Commit Messages
    shell.run:
      command: ["git", "log", "{{.inputs.base_branch}}..HEAD", "--oneline"]

  - id: reviews
    name: Parallel Persona Reviews
    type: parallel
    max_concurrency: 3
    steps:
      - id: security_review
        name: Security Review
        type: llm
        model: strategic
        condition:
          expression: '"security" in inputs.personas'
        system: |
          You are a security engineer reviewing code changes for vulnerabilities.
          Focus on:
          - Input validation and sanitization
          - Authentication and authorization issues
          - Injection attacks (SQL, command, XSS)
          - Sensitive data exposure
          - Cryptography issues

          Rate each finding as: CRITICAL, HIGH, MEDIUM, or LOW severity.
          Be specific about file names and line context.
        prompt: |
          Review these code changes for security issues:

          **Branch:** {{.steps.get_branch.stdout}}
          **Commits:**
          {{.steps.get_commits.stdout}}

          **Changes:**
          {{.steps.get_diff.stdout}}

          Provide a structured security review with:
          1. Executive summary (1-2 sentences)
          2. Findings (if any) with severity ratings
          3. Recommendations

      - id: performance_review
        name: Performance Review
        type: llm
        model: balanced
        condition:
          expression: '"performance" in inputs.personas'
        system: |
          You are a performance engineer reviewing code for efficiency issues.
          Focus on:
          - Algorithmic complexity (O(n²), unnecessary loops)
          - Memory allocation and leaks
          - Database query efficiency (N+1 queries, missing indexes)
          - Caching opportunities
          - Resource cleanup

          Rate each finding as: CRITICAL, HIGH, MEDIUM, or LOW impact.
        prompt: |
          Review these code changes for performance issues:

          **Branch:** {{.steps.get_branch.stdout}}
          **Commits:**
          {{.steps.get_commits.stdout}}

          **Changes:**
          {{.steps.get_diff.stdout}}

          Provide a structured performance review with:
          1. Executive summary (1-2 sentences)
          2. Findings (if any) with impact ratings
          3. Optimization recommendations

      - id: style_review
        name: Code Style Review
        type: llm
        model: fast
        condition:
          expression: '"style" in inputs.personas'
        system: |
          You are a code quality reviewer focused on readability and maintainability.
          Focus on:
          - Naming conventions (variables, functions, types)
          - Code organization and structure
          - Documentation and comments
          - Error handling patterns
          - Idiomatic code usage

          Rate each finding as: SUGGESTION, MINOR, or IMPORTANT.
          Be constructive and specific.
        prompt: |
          Review these code changes for style and maintainability:

          **Branch:** {{.steps.get_branch.stdout}}
          **Commits:**
          {{.steps.get_commits.stdout}}

          **Changes:**
          {{.steps.get_diff.stdout}}

          Provide a structured style review with:
          1. Executive summary (1-2 sentences)
          2. Findings (if any) with severity
          3. Improvement suggestions

  - id: generate_report
    name: Generate Review Report
    type: llm
    model: balanced
    prompt: |
      Generate a comprehensive code review report in Markdown format.

      ## Context
      - **Branch:** {{.steps.get_branch.stdout}}
      - **Base:** {{.inputs.base_branch}}
      - **Commits:**
      {{.steps.get_commits.stdout}}

      ## Reviews

      {{if .steps.reviews.security_review}}
      ### Security Review
      {{.steps.reviews.security_review.response}}
      {{end}}

      {{if .steps.reviews.performance_review}}
      ### Performance Review
      {{.steps.reviews.performance_review.response}}
      {{end}}

      {{if .steps.reviews.style_review}}
      ### Style Review
      {{.steps.reviews.style_review.response}}
      {{end}}

      Create a well-formatted Markdown report with:
      1. A header with branch info and date
      2. An overall summary with a recommendation (APPROVE, REQUEST_CHANGES, or NEEDS_DISCUSSION)
      3. Each review section (only include sections that have content)
      4. A prioritized action items list combining all findings
      5. A conclusion

      Output ONLY the Markdown content, no code fences.

  - id: write_report
    name: Write Report File
    file.write:
      path: "{{.inputs.output_file}}"
      content: "{{.steps.generate_report.response}}"

outputs:
  - name: report_path
    type: string
    value: "{{.inputs.output_file}}"
    description: Path to the generated review report

  - name: branch
    type: string
    value: "{{.steps.get_branch.stdout}}"
    description: Branch that was reviewed

  - name: summary
    type: string
    value: "{{.steps.generate_report.response}}"
    description: Full review report content
