name: nightly-build-summary
description: Aggregate overnight CI results and deliver a morning digest to Slack
version: "1.0"

schedule: "0 7 * * 1-5"  # 7am weekdays

inputs:
  - name: repo
    type: string
    description: Repository in owner/repo format
    required: true

  - name: hours_back
    type: number
    default: 12
    description: Hours to look back for runs

  - name: slack_channel
    type: string
    default: "#ci-digest"
    description: Slack channel for the digest

steps:
  - id: get_workflows
    name: List Workflows
    github.list_workflows:
      repo: "{{.inputs.repo}}"

  - id: get_runs
    name: Get Recent Runs
    github.list_workflow_runs:
      repo: "{{.inputs.repo}}"
      created: ">={{now | date_modify \"-12h\" | date \"2006-01-02\"}}"
      per_page: 100

  - id: aggregate_stats
    name: Aggregate Statistics
    type: llm
    model: fast
    system: |
      Aggregate CI run statistics into structured data.

      Compute:
      - total_runs: count
      - passed: count
      - failed: count
      - pass_rate: percentage
      - by_workflow: map of workflow name to {runs, passed, failed}
      - by_branch: map of branch to {runs, passed, failed}
      - avg_duration: average run duration in minutes
      - failures: list of {workflow, run_id, branch, error_summary}

      Return as JSON.
    prompt: |
      Aggregate these CI runs from the last {{.inputs.hours_back}} hours:

      {{range .steps.get_runs.response.workflow_runs}}
      - Workflow: {{.name}}
        Run: {{.id}}
        Status: {{.conclusion}}
        Branch: {{.head_branch}}
        Duration: {{.run_started_at}} to {{.updated_at}}
        Trigger: {{.event}}
      {{end}}

      Return aggregated statistics as JSON.

  - id: detect_patterns
    name: Detect Failure Patterns
    type: llm
    model: balanced
    system: |
      Analyze CI failures to detect patterns.

      Look for:
      1. **Flaky Tests**: Same test passing and failing on same code
      2. **Recurring Failures**: Same failure multiple times
      3. **New Failures**: First occurrence of a failure
      4. **Infrastructure Issues**: Timeouts, resource exhaustion

      For each pattern found, note:
      - Type: flaky, recurring, new, infrastructure
      - Details: what's failing
      - Frequency: how often
      - Recommendation: what to do
    prompt: |
      Analyze these CI runs for failure patterns:

      **Statistics:**
      {{.steps.aggregate_stats.response}}

      **Recent Runs:**
      {{range .steps.get_runs.response.workflow_runs}}
      {{if eq .conclusion "failure"}}
      - {{.name}} #{{.run_number}}: {{.conclusion}}
        Branch: {{.head_branch}}
        SHA: {{.head_sha}}
      {{end}}
      {{end}}

      Identify patterns and provide recommendations.

  - id: compare_trends
    name: Compare to Last Week
    type: llm
    model: fast
    prompt: |
      Compare current stats to expected baseline:

      **Current (last {{.inputs.hours_back}} hours):**
      {{.steps.aggregate_stats.response}}

      Assess:
      - Is pass rate above/below normal (assume 95% baseline)?
      - Are there more failures than usual?
      - Any concerning trends?

      Keep assessment brief - 2-3 bullet points.

  - id: generate_digest
    name: Generate Digest
    type: llm
    model: balanced
    system: |
      Generate a morning CI digest that's:
      - Scannable in 30 seconds
      - Focused on actionable items
      - Clear about what needs attention vs what's fine

      Use tables for statistics, bullet points for actions.
    prompt: |
      Generate a morning CI digest:

      **Statistics:**
      {{.steps.aggregate_stats.response}}

      **Patterns Detected:**
      {{.steps.detect_patterns.response}}

      **Trend Analysis:**
      {{.steps.compare_trends.response}}

      Format as Markdown:

      # Morning CI Digest - [date]

      ## Overview
      **Last {{.inputs.hours_back}} hours:** X runs | Y passed (Z%) | W failed

      [1 sentence summary - "Green overnight" or "Some issues need attention"]

      ## By Workflow
      | Workflow | Runs | Pass Rate | Avg Time |
      |----------|------|-----------|----------|
      [table rows]

      ## Failures Needing Attention
      [Only if there are failures]
      ### 1. [failure name]
      - **Failed X times**
      - Error: [brief error]
      - **Action:** [what to do]

      ## Patterns Detected
      [flaky tests, recurring issues]

      ## Trends
      [brief trend comparison]

      ---
      *Digest by Conductor*

  - id: post_slack
    name: Post to Slack
    slack.post_message:
      channel: "{{.inputs.slack_channel}}"
      text: "{{.steps.generate_digest.response}}"

outputs:
  - name: digest
    type: string
    value: "{{.steps.generate_digest.response}}"
    description: Full CI digest

  - name: pass_rate
    type: number
    value: "{{.steps.aggregate_stats.response.pass_rate}}"
    description: Overall pass rate percentage
