# typed: false
# frozen_string_literal: true

# This is a template formula for Conductor.
# The actual formula is auto-generated by GoReleaser and published to:
# https://github.com/tombee/homebrew-tap
#
# This file serves as a reference for the formula structure.

class Conductor < Formula
  desc "LLM workflow orchestration tool"
  homepage "https://github.com/tombee/conductor"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tombee/conductor/releases/download/v0.0.1/conductor_0.0.1_darwin_arm64.tar.gz"
      sha256 "" # Will be filled by GoReleaser
    end
    if Hardware::CPU.intel?
      url "https://github.com/tombee/conductor/releases/download/v0.0.1/conductor_0.0.1_darwin_amd64.tar.gz"
      sha256 "" # Will be filled by GoReleaser
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tombee/conductor/releases/download/v0.0.1/conductor_0.0.1_linux_arm64.tar.gz"
      sha256 "" # Will be filled by GoReleaser
    end
    if Hardware::CPU.intel?
      url "https://github.com/tombee/conductor/releases/download/v0.0.1/conductor_0.0.1_linux_amd64.tar.gz"
      sha256 "" # Will be filled by GoReleaser
    end
  end

  license "Apache-2.0"

  def install
    bin.install "conductor"
  end

  test do
    system "#{bin}/conductor", "version"
  end
end
