name: pr-size-gate
description: Analyze PR size and complexity, suggest splits for oversized changes
version: "1.0"

inputs:
  - name: repo
    type: string
    description: Repository in owner/repo format
    required: true

  - name: pr_number
    type: number
    description: PR number to analyze
    required: true

  - name: thresholds
    type: object
    default:
      good: 200
      acceptable: 400
      large: 800
      oversized: 1500
    description: Line count thresholds

  - name: ignored_patterns
    type: array
    default:
      - "*.generated.*"
      - "*.lock"
      - "go.sum"
      - "package-lock.json"
      - "yarn.lock"
    description: File patterns to exclude from analysis

steps:
  - id: get_pr
    name: Get PR Details
    github.get_pull:
      repo: "{{.inputs.repo}}"
      pull_number: "{{.inputs.pr_number}}"

  - id: get_files
    name: Get Changed Files
    github.list_pull_files:
      repo: "{{.inputs.repo}}"
      pull_number: "{{.inputs.pr_number}}"

  - id: compute_metrics
    name: Compute Size Metrics
    type: llm
    model: fast
    system: |
      Analyze the PR files and compute metrics.

      Ignore files matching these patterns: {{.inputs.ignored_patterns}}

      Compute:
      - total_additions: lines added
      - total_deletions: lines deleted
      - total_changes: additions + deletions
      - files_changed: count of files
      - file_types: map of extension to count
      - test_lines: lines in test files
      - code_lines: lines in non-test files

      Return as JSON.
    prompt: |
      Compute metrics for this PR:

      {{range .steps.get_files.response}}
      - {{.filename}}: +{{.additions}} -{{.deletions}}
      {{end}}

      Return JSON with metrics.

  - id: classify_change
    name: Classify Change Type
    type: llm
    model: balanced
    system: |
      Classify this PR by type and scope.

      Types:
      - feature: New functionality
      - bugfix: Bug fix
      - refactor: Code restructuring without behavior change
      - config: Configuration changes
      - docs: Documentation
      - test: Test additions/changes
      - mixed: Multiple types

      Scope:
      - single_component: Changes one area
      - cross_cutting: Touches multiple areas
      - infrastructure: Build/CI/tooling

      Risk Areas (flag if touched):
      - security: Auth, crypto, input validation
      - data: Database schemas, migrations
      - api: Public API changes
      - performance: Hot paths, algorithms
    prompt: |
      Classify this PR:

      **Title:** {{.steps.get_pr.response.title}}
      **Description:** {{.steps.get_pr.response.body | truncate 500}}

      **Files:**
      {{range .steps.get_files.response}}
      - {{.filename}}: +{{.additions}} -{{.deletions}}
      {{end}}

      Return:
      - type: [type]
      - scope: [scope]
      - risk_areas: [list]
      - summary: [1-2 sentence description]

  - id: assess_reviewability
    name: Assess Reviewability
    type: llm
    model: balanced
    prompt: |
      Assess how reviewable this PR is.

      **Metrics:** {{.steps.compute_metrics.response}}
      **Classification:** {{.steps.classify_change.response}}
      **Thresholds:** {{.inputs.thresholds}}

      Determine:
      1. **Size Rating**: GOOD, ACCEPTABLE, LARGE, or OVERSIZED
      2. **Estimated Review Time**: in minutes
      3. **Review Confidence**: How likely is a thorough review?

      Consider:
      - Line count vs thresholds
      - Complexity of changes (not just size)
      - Whether it's mostly generated/config vs logic
      - Test coverage of changes

  - id: suggest_splits
    name: Suggest Splits
    condition:
      expression: 'contains(steps.assess_reviewability.response, "LARGE") || contains(steps.assess_reviewability.response, "OVERSIZED")'
    type: llm
    model: strategic
    system: |
      You are a senior developer suggesting how to split a large PR.

      Good splits:
      - Are independently reviewable and mergeable
      - Have clear boundaries (by feature, layer, or file group)
      - Can be ordered logically (foundation first)

      Consider:
      - Database/schema changes first (foundation)
      - Backend logic next
      - Frontend last (depends on backend)
      - Tests with their corresponding code

      Be specific about which files go in each split.
    prompt: |
      This PR is too large. Suggest how to split it:

      **Title:** {{.steps.get_pr.response.title}}
      **Classification:** {{.steps.classify_change.response}}

      **Files:**
      {{range .steps.get_files.response}}
      - {{.filename}}: +{{.additions}} -{{.deletions}}
      {{end}}

      Suggest 2-4 logical splits with:
      1. **Name** of the split PR
      2. **Files** to include
      3. **Order** (which to merge first)
      4. **Rationale** for this grouping

  - id: generate_comment
    name: Generate PR Comment
    type: llm
    model: balanced
    prompt: |
      Generate a PR size analysis comment:

      **Metrics:** {{.steps.compute_metrics.response}}
      **Classification:** {{.steps.classify_change.response}}
      **Reviewability:** {{.steps.assess_reviewability.response}}
      {{if .steps.suggest_splits}}
      **Split Suggestions:** {{.steps.suggest_splits.response}}
      {{end}}

      Format as Markdown:

      ## PR Size Analysis

      **Lines Changed:** X (+Y, -Z)
      **Files Changed:** N
      **Classification:** [type] ([scope])

      ### Assessment: [emoji] [GOOD/ACCEPTABLE/LARGE/OVERSIZED]

      [1-2 sentence summary]

      **Estimated Review Time:** X minutes
      **Review Confidence:** [High/Moderate/Low]

      {{if large or oversized}}
      ### Suggested Splits
      [numbered list with files and rationale]
      {{end}}

      ### Risk Areas
      [list any flagged risk areas]

      ---
      *Size analysis by Conductor*

  - id: post_comment
    name: Post Comment
    github.create_issue_comment:
      repo: "{{.inputs.repo}}"
      issue_number: "{{.inputs.pr_number}}"
      body: "{{.steps.generate_comment.response}}"

outputs:
  - name: size_rating
    type: string
    value: "{{.steps.assess_reviewability.response}}"
    description: Size assessment

  - name: needs_split
    type: boolean
    value: "{{or (contains .steps.assess_reviewability.response \"LARGE\") (contains .steps.assess_reviewability.response \"OVERSIZED\")}}"
    description: Whether the PR should be split
