name: release-notes-generator
description: Generate release notes from commits and PRs since the last release
version: "1.0"

inputs:
  - name: repo
    type: string
    description: Repository in owner/repo format
    required: true

  - name: from_tag
    type: string
    description: Starting tag (defaults to latest tag)

  - name: to_ref
    type: string
    default: "HEAD"
    description: Ending ref (tag, branch, or SHA)

  - name: include_contributors
    type: boolean
    default: true
    description: Include contributor acknowledgments

  - name: output_file
    type: string
    default: "RELEASE_NOTES.md"
    description: Output file path

steps:
  - id: get_latest_tag
    name: Get Latest Tag
    condition:
      expression: 'inputs.from_tag == ""'
    shell.run:
      command: ["git", "describe", "--tags", "--abbrev=0"]

  - id: determine_range
    name: Determine Version Range
    shell.run:
      command: |
        if [ -n "{{.inputs.from_tag}}" ]; then
          echo "{{.inputs.from_tag}}"
        else
          echo "{{.steps.get_latest_tag.stdout | trim}}"
        fi

  - id: get_commits
    name: Get Commits in Range
    shell.run:
      command: ["git", "log", "{{.steps.determine_range.stdout | trim}}..{{.inputs.to_ref}}", "--pretty=format:%H|%s|%an|%ae", "--no-merges"]

  - id: get_prs
    name: Get Merged PRs
    github.list_pulls:
      repo: "{{.inputs.repo}}"
      state: closed
      sort: updated
      direction: desc
      per_page: 100

  - id: categorize_changes
    name: Categorize Changes
    type: llm
    model: balanced
    system: |
      You are a technical writer categorizing changes for release notes.

      Categorize each change into ONE of these categories:
      - Features: New functionality
      - Bug Fixes: Corrections to existing functionality
      - Breaking Changes: Changes requiring user action
      - Performance: Speed or resource improvements
      - Documentation: Doc updates
      - Dependencies: Dependency updates
      - Internal: Refactoring, tests, CI changes

      For Breaking Changes, always note what users need to do.

      Output as JSON array with objects containing:
      {
        "category": "category name",
        "title": "user-friendly title",
        "description": "brief description",
        "pr": PR number or null,
        "breaking_migration": "migration steps if breaking, else null"
      }
    prompt: |
      Categorize these commits from {{.steps.determine_range.stdout | trim}} to {{.inputs.to_ref}}:

      ## Commits
      {{.steps.get_commits.stdout}}

      ## Recent Merged PRs (for context)
      {{range .steps.get_prs.response}}
      {{if .merged_at}}
      - #{{.number}}: {{.title}}
        Labels: {{range .labels}}{{.name}} {{end}}
        Body: {{.body | truncate 200}}
      {{end}}
      {{end}}

      Return a JSON array of categorized changes.

  - id: generate_notes
    name: Generate Release Notes
    type: llm
    model: balanced
    system: |
      You are a technical writer creating release notes.

      Write clear, user-focused release notes that:
      - Lead with the most impactful changes
      - Use active voice ("Added X" not "X was added")
      - Include PR/issue links where available
      - Highlight breaking changes prominently
      - Keep descriptions concise (1-2 lines each)

      Format as clean Markdown without code fences around the output.
    prompt: |
      Generate release notes for version {{.inputs.to_ref}}.

      Previous version: {{.steps.determine_range.stdout | trim}}

      Categorized changes:
      {{.steps.categorize_changes.response}}

      {{if .inputs.include_contributors}}
      Include a Contributors section thanking authors.
      {{end}}

      Format:
      # [version] (YYYY-MM-DD)

      ## Highlights
      [1-3 bullet summary of biggest changes]

      ## Features
      - **Feature name**: Description (#PR)

      ## Bug Fixes
      ...

      ## Breaking Changes
      ...
      [Include migration steps]

      ## Contributors
      Thanks to @user1, @user2...

  - id: write_notes
    name: Write Release Notes
    file.write:
      path: "{{.inputs.output_file}}"
      content: "{{.steps.generate_notes.response}}"

outputs:
  - name: notes
    type: string
    value: "{{.steps.generate_notes.response}}"
    description: Generated release notes

  - name: output_path
    type: string
    value: "{{.inputs.output_file}}"
    description: Path to the release notes file
