name: build-failure-triage
description: Analyze CI build failures, classify as transient or real, and post summary to Slack
version: "1.0"

inputs:
  - name: repo
    type: string
    description: Repository in owner/repo format
    required: true

  - name: run_id
    type: string
    description: GitHub Actions run ID that failed
    required: true

  - name: slack_channel
    type: string
    default: "#ci-alerts"
    description: Slack channel for notifications

steps:
  - id: fetch_run
    name: Fetch Workflow Run Details
    github.get_workflow_run:
      repo: "{{.inputs.repo}}"
      run_id: "{{.inputs.run_id}}"

  - id: fetch_logs
    name: Fetch Build Logs
    github.get_workflow_run_logs:
      repo: "{{.inputs.repo}}"
      run_id: "{{.inputs.run_id}}"

  - id: fetch_commits
    name: Get Recent Commits
    github.list_commits:
      repo: "{{.inputs.repo}}"
      sha: "{{.steps.fetch_run.response.head_sha}}"
      per_page: 10

  - id: fetch_last_success
    name: Find Last Successful Run
    github.list_workflow_runs:
      repo: "{{.inputs.repo}}"
      workflow_id: "{{.steps.fetch_run.response.workflow_id}}"
      status: success
      per_page: 1

  - id: analyze_failure
    name: Analyze Build Failure
    type: llm
    model: strategic
    system: |
      You are a senior SRE analyzing CI build failures. Your job is to:
      1. Classify the failure as TRANSIENT or REAL
      2. Identify the root cause
      3. Suggest the likely culprit commit if applicable
      4. Recommend an action

      TRANSIENT failures include:
      - Network timeouts, DNS failures
      - Flaky tests (passed before, fails intermittently)
      - Resource exhaustion (OOM, disk full)
      - External service unavailability
      - Rate limiting

      REAL failures include:
      - Compilation errors
      - Test failures from code changes
      - Missing dependencies
      - Configuration errors
      - Type errors

      Be specific about file names and error messages.
    prompt: |
      Analyze this build failure:

      **Repository:** {{.inputs.repo}}
      **Run ID:** {{.inputs.run_id}}
      **Branch:** {{.steps.fetch_run.response.head_branch}}
      **Commit:** {{.steps.fetch_run.response.head_sha}}
      **Triggered by:** {{.steps.fetch_run.response.event}}

      ## Build Logs (truncated)
      ```
      {{.steps.fetch_logs.response | truncate 8000}}
      ```

      ## Recent Commits
      {{range .steps.fetch_commits.response}}
      - {{.sha | truncate 7}}: {{.commit.message | truncate 80}} ({{.commit.author.name}})
      {{end}}

      ## Last Successful Run
      {{if .steps.fetch_last_success.response}}
      SHA: {{(index .steps.fetch_last_success.response 0).head_sha}}
      {{else}}
      No previous successful run found
      {{end}}

      Provide your analysis in this format:

      **Classification:** [TRANSIENT or REAL]
      **Confidence:** [HIGH, MEDIUM, or LOW]
      **Category:** [test, build, lint, deploy, infrastructure]

      **Summary:** [1-2 sentence summary of the failure]

      **Root Cause:** [Detailed explanation of what went wrong]

      **Likely Culprit:** [Commit SHA and author if applicable, or "N/A" for transient]

      **Recommended Action:** [What should be done - retry, investigate, revert, etc.]

  - id: post_slack
    name: Post to Slack
    slack.post_message:
      channel: "{{.inputs.slack_channel}}"
      text: |
        {{if contains .steps.analyze_failure.response "TRANSIENT"}}:warning:{{else}}:red_circle:{{end}} *Build Failed: {{.inputs.repo}}*

        *Run:* <https://github.com/{{.inputs.repo}}/actions/runs/{{.inputs.run_id}}|#{{.inputs.run_id}}>
        *Branch:* `{{.steps.fetch_run.response.head_branch}}`
        *Commit:* `{{.steps.fetch_run.response.head_sha | truncate 7}}`

        {{.steps.analyze_failure.response}}

        <https://github.com/{{.inputs.repo}}/actions/runs/{{.inputs.run_id}}|View Logs>

outputs:
  - name: classification
    type: string
    value: "{{.steps.analyze_failure.response}}"
    description: Full analysis of the build failure

  - name: run_url
    type: string
    value: "https://github.com/{{.inputs.repo}}/actions/runs/{{.inputs.run_id}}"
    description: URL to the failed run
